### ISSUE TITLE
Duplicate data sent to sinks

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/heapster#107]
While writing the GCM sink I found that Heapster sent a lot of duplicate data to the sinks. Something along the lines of:

Container: /  - Time: 0s-10s
Container: /  - Time: 0s-10s
Container: /  - Time: 0s-10s
Container: /  - Time: 30s-40s
Container: /  - Time: 30s-40s
Container: /  - Time: 30s-40s
Container: /  - Time: 60s-70s
Container: /  - Time: 60s-70s
Container: /  - Time: 60s-70s

**Comment by vishh** [comment]
I will take a look at this issue today.

**Comment by pires** [comment]
Any updates on this?

**Comment by vishh** [comment]
I fixed some heapster side bugs that should address this issue. There is still the dynamic housekeeping issue in Cadvisor. Now that cadvisor exposes a time range for stats, I will update heapster to use that time range.
