### ISSUE TITLE
Collect and export kubernetes events and docker events 

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/heapster#118]
InfluxDB supports events natively. Other backends might not. We can place structure around some specific events like container starts, deletions, restarts, etc and export them as metrics, but that might be sub-optimal.
Need to explore how events is currently handled by various monitoring/alerting systems.

**Comment by vishh** [comment]
@saad-ali is working on this.

**Comment by saad-ali** [comment]
#252
