### ISSUE TITLE
Proxy calls to InfluxDB with nginx

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/heapster#135]
So, having something like
```
yaml
- name: "INFLUXDB_HOST"
  value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
```
is very limitative when it comes to running ```influxdb``` + ```grafana```, especially inside Kubernetes.

See [my suggested solution](https://github.com/GoogleCloudPlatform/kubernetes/issues/4841).

**Comment by vishh** [comment]
+1 to making this change. As long as it works on most kubernetes cluster
setups, I am fine with that change.

**Comment by pires** [comment]
In progress..
