### ISSUE TITLE
heapster and kubernetes: not getting any container stats

### ISSUE THREAD

**Issue by jeinwag** [GoogleCloudPlatform/heapster#15]
I'm currently testing heapster with kubernetes v0.5 and cadvisor 0.6.2.

Grafana doesn't display any graphs with per container stats (total cluster CPU and memory usage is displayed fine), it's just giving the error "Couldn't look up columns for series: stats"

Heapster is also displaying errors constantly:

    E1121 09:30:41.665006 00007 kube.go:104] failed to get stats from kubelet on host with ip   192.168.200.230 - Got 'Internal Error: unable to unmarshal container info for "/docker/35c89c2b64d4d76ffda3cd7e3797273a6ba829bae81ca15364ed35765b546fbb" (failed to get container "/docker/35c89c2b64d4d76ffda3cd7e3797273a6ba829bae81ca15364ed35765b546fbb" with error: unknown container "/docker/35c89c2b64d4d76ffda3cd7e3797273a6ba829bae81ca15364ed35765b546fbb"
    ): invalid character 'i' in literal false (expecting 'l')
    ': invalid character 'I' looking for beginning of value

So I guess there's some problem with getting the data from cadvisor into InfluxDB?

Best regards,
Julian

**Comment by vishh** [comment]
@Fandekasp: Kubernetes is using the latest version of cadvisor. Can you try upgrading cadvisor and see if that fixes your issues?
