### ISSUE TITLE
Influxdb clustering

### ISSUE THREAD

**Issue by jimmidyson** [GoogleCloudPlatform/heapster#174]
Unless I'm missing something, currently the heapster manifests for influxdb will only support a single Influxdb instance. Clustering Influxdb will probably be necessary for any reasonable size deployment. I assume this would be achieved by updating the seeds in the config.toml but I'm not sure of the best way to retrieve those seed servers?

**Comment by vishh** [comment]
Support for [peer to peer services](https://github.com/GoogleCloudPlatform/kubernetes/issues/1607) is still being designed in kubernetes. Once that is finalized, adding support for clustering should be straight forward.

**Comment by jimmidyson** [comment]
Not really a heapster problem - closing.
