### ISSUE TITLE
Support multiple backends 

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/heapster#197]
This is required to support Google Cloud Monitoring for metrics and Google Cloud Logging for events simultaneously.

**Comment by jimmidyson** [comment]
@vishh - I have a prototype for this outside of heapster in kadvisor (https://github.com/jimmidyson/kadvisor) that I was working on to learn more about go. The principal is to go from multiple sources, through a pipeline & sending to multiple sinks. Currently the pipeline just acts as a intermediary to pass messages from sinks to sinks & decouple sources & sinks, but could in future be used to validate input, etc.

The use of channels also means that collection is done in different goroutines to sinks storing data (#110) & allows you to specify different collection intervals per source.

What I'd like to do is to migrate what I've done for kadvisor to heapster & plug in the sources/sinks that you already have in heapster. I'd like to migrate the command line flags at the same time as specified in #200.

What do you think? I know this is quite a significant change but I think it would bring a lot of benefits.

**Comment by jimmidyson** [comment]
Of course this approach could also be used for monitoring multiple Kubernetes clusters, or even for federation.

**Comment by vishh** [comment]
That sounds like a good idea.
I have also been doing some work on adding in-memory cache for metrics and
events. I was imagining having sources write data to the cache and sinks
pulling data off of the cache in a sampling rate of their choice. WDYT?

**Comment by jimmidyson** [comment]
I think that approach would work well for exposing data to be pulled/scraped by external services, e.g. prometheus. I see this in-memory cache as one example of a sink, just one that doesn't push the data anywhere, just exposes it for external reaping.

Having it used in process for push only sinks seems like an unnecessary overhead. If data is being pushed then why not push it as it's collected? Push sinks could do their own throttling of data, but keeping an in-memory cache of metrics when all you're trying to do is push to external sinks seems like a use of resources. Normally when pushing metrics you would configure the sampling rate at the source & push the data.

**Comment by vishh** [comment]
There is a need to expose some of the metrics via a REST endpoint. So the
cache will be necessary then.

We can also set it up in a such a way that the in-process sinks will
immediately receive data and can themselves decide on when to publish the
data. I guess I am moving towards a hybrid solution that combines an
in-memory cache and a channel model.

Another thing to consider is that if sinks are performing their own
caching, then we might end up duplicating data in multiple sinks until the
data is flushed. Having a central cache helps keep the sink logic simple -
the sinks can retry on failure or fallback to their default policy on
success.

This is just a brain dump. I am happy to be convinced otherwise.

**Comment by vishh** [comment]
@jimmidyson: Any thoughts here? I did some minor updates to the sources code (#220) over the weekend. This should make adding multiple sinks straight forward with the current architecture, until we have a better solution.

**Comment by jimmidyson** [comment]
@vishh - saw your changes. Happy to go with the in-memory representation for now & see how it works out.

As for configuration of backends, how would you feel about dropping the individual `-kubernetes_master`, `-coreos`, etc flags & move to a more generic `--source=<source_type>:<source_config>` flag definition. We could then use the new factory methods you've added in & side-effect imports to add in source & sink extensions/plugins? e.g. if I wanted to use kubernetes source I would use something like:

    --source=kubernetes:<optional_kubernetes_master>?insecure=true&kubelet-port=10250&auth=/etc/heapster/clientauth.json

The `--source` flags & complementary `--sink`flags could both be specified multiple times.

This approach would make adding sources/sinks much easier IMO.

**Comment by vishh** [comment]
I like the basic idea.  Wouldn't combining all the options for a given
source or sink be tedious when run manually though? Another option is to
add structure to flag names. Or we can ditch flags altogether and take in a
config file.

**Comment by jimmidyson** [comment]
Heapster isn't a command you're going to be running over & over again on the command line. It's normally going to be configured in a Docker container so config specified in Dockerfile or Kubernetes manifest. Or as a service where it will again only be configured in e.g. a systemd unit file. Once you have it right you're not going to change it very often.

I'm not sure how we could structure flags to achieve the same pluggable approach?

As for ditching flags, I totally go for adding a config file option as an alternative, but wouldn't ditch flags as on the whole I think it will only be a handful of flags that are used.

**Comment by vishh** [comment]
Most of the manual runs are for testing. Automated testing can address that issue to some extent. Your argument is sound!

As for flags, the format could be something like `sources.<source_type>.<option>` - e.x.: `--sources.kube.master=http://kubernetes-ro/ --sources.kube.auth-file="/path/to/auth/file" --sources.coreos.fleet-endpoints="127.0.0.1" `

I like config file. Its simple. The same format could be used to enable dynamic configuration. I find static configuration to be a major issue with many existing monitoring and logging solutions. So I intend to evolve heapster to support config updates.

I am fine with merging this PR and replace this with a config file once either of us has some spare cycles.
