### ISSUE TITLE
Consolidate flags into one place

### ISSUE THREAD

**Issue by jimmidyson** [GoogleCloudPlatform/heapster#200]
Currently flags are spread about all over different source files. Consolidating in one place will make addition of flags more consistent & prevent accidentally reusing flag names, etc.

As an extra, can we consider switching to `pflag` (https://github.com/spf13/pflag/), drop in replacement for `flag`, but POSIX compliant flags & has shorthand flags, etc?

**Comment by jimmidyson** [comment]
Could even consider viper (https://github.com/spf13/viper) so we can combine flags, env vars & config files into one runtime configuration. As we as more functionality, multiple sinks, events, etc, having a config file might be really useful, in addition to flags, etc.

**Comment by vishh** [comment]
I like this idea. Most of heapster can act as a library with this change. `viper` sounds pretty interesting. It should satisfy most of the deployment scenarios.

**Comment by jimmidyson** [comment]
Think this is closeable note that sources & sinks flags are consolidated.
