### ISSUE TITLE
something wrong in grafana service

### ISSUE THREAD

**Issue by Andre-Freitas** [GoogleCloudPlatform/heapster#203]
Today i have pull the latest changes to this repository, but i think you still have an issue when collecting influxdb data.
If i don't change env variables "INFLUXDB_HOST" and "INFLUXDB_EXTERNAL_URL" (in heapster/deploy/kube-config/influxdb-grafana-controller.yaml), my grafana will try to check influxdb in http://monitoring-influxdb/api/v1beta1/proxy/services/monitoring-influxdb/db which for me it will not work because my apiserver is not working in the same server (i'm using ppires k8s cluster which only runs docker in minions).
If you want to find influxdb db trought api server, shouldn't you change INFLUXDB_HOST for 'kubernetes-ro' instead of 'monitoring-influxdb' in your rc?

**Comment by Andre-Freitas** [comment]
plus the error above i'm detecting this second error /set_basic_auth.sh: line 10: [: ==: unary operator expected in grafana logs
http://ur1.ca/k1eox

**Comment by vishh** [comment]
@Andre-Freitas: A new release for heapster and Grafana will be out today or tomorrow. I would suggest trying with that.

**Comment by vishh** [comment]
@Andre-Freitas: Can you try out the latest release (v0.10.0) and see if it works for you?

**Comment by Andre-Freitas** [comment]
@vishh I have deployed the latest version from github, but now my grafana web page is giving 404 page not found regarding at each graph http://postimg.org/image/7ahbhrzj3/ 
Regarding the logs of each container: http://ur1.ca/k4916
Regarding heapster webpage: http://ur1.ca/k491g

**Comment by vishh** [comment]
From the logs you provided everything seems to be fine. Can you get seom
client side logs from the browser while using Grafana? Is the kube
apiserver accessible from outside the cluster? Is it running on non-default
port?

**Comment by Andre-Freitas** [comment]
Ok i repetead the instalation of heaspter and now i have found the cause of the problem (you still assume that apiserver is in the same ip of the grafana service).
Let me explain:
1º At this moment i have the following services http://ur1.ca/k4hom
2º When i start a browser to open grafana web page http://10.100.163.163/#/dashboard/file/kubernetes.json i get a lot of errors 404 in browser http://ur1.ca/k4hpc  (because grafana is trying to querying the apiserver using grafana ip service - which will not work)
3º if i get one of the querys that is giving 404 (for example, http://10.100.163.163/api/v1beta1/proxy/services/monitoring-grafana/db/k8s/series?p=root&q=select+container_name,+mean(value)+from+%22memory%2Fworking_set_bytes_gauge%22+where+time+%3E+now()+-+5m+and+labels+%3D~+%2Fname:influxGrafana%2F+group+by+time(2s),+container_name+order+asc&u=root) and change it to use the ip of the service kubernetes-ro, i get the correct results http://ur1.ca/k4hrn (http://10.100.0.1/api/v1beta1/proxy/services/monitoring-grafana/db/k8s/series?p=root&q=select+container_name,+mean(value)+from+%22memory%2Fworking_set_bytes_gauge%22+where+time+%3E+now()+-+5m+and+labels+%3D~+%2Fname:influxGrafana%2F+group+by+time(2s),+container_name+order+asc&u=root)

The problem is in the way that grafana trys to query influxdb trough apiserver - all querys should use the kubernetes-ro ip service and instead its using is own ip on the querys

**Comment by jimmidyson** [comment]
The grafana image has been updated in master & these issues should go away once we release that & update manifests. @vishh - any chance of that happening soon?

**Comment by Andre-Freitas** [comment]
After a IRC chat with @vishh the problem was resolved when i removed the following env variable from influxdb-grafana-controller.yaml

  - name: "INFLUXDB_EXTERNAL_URL"
value: '/api/v1beta1/proxy/services/monitoring-grafana/db/'
