### ISSUE TITLE
Avoid duplicate kube events in InfluxDB

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/heapster#250]
We can use the UID of kube events as the sequence number while writing to influxdb. That combined with the timestamp in the event will help avoid duplicates in Influxdb.

**Comment by saad-ali** [comment]
This would be super sweet, but it it looks like `sequence_number` can not be an arbitrary string.
```
failed to write events to influxDB - Server returned (400): sequence_number field must be float but is string (43e8c11b-e94c-11e4-a7c2-42010af0f6db)
```

**Comment by vishh** [comment]
Can we have some generic one to one mapping from a uid to a float?
