### ISSUE TITLE
Is coreos integration broken in v0.11.0?

### ISSUE THREAD

**Issue by rvadim** [GoogleCloudPlatform/heapster#273]
Currently i can't find any up to date docs about how to running heapster on coreos.
If i try to put --coreos parameter or --fleet_endpoints heapster print help with:
```
flag provided but not defined: -coreos
```
Is coreos support dropped or I need to use specific environment variables?

**Comment by vishh** [comment]
I apologize for the confusion. The support is still intact. The
configuration has changed. Take a look here
<https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/source-configuration.md>
.
We had to update the configuration semantics to make it possible to support
more sources in the future.

**Comment by rvadim** [comment]
Thank you, it's now works.

systemd unit file now looks like this:
```
[Unit]
Description=Heapster monitoring tool for cluster
After=docker.service
Requires=docker.service

[Service]                                                                                                                                                     
ExecStartPre=-/usr/bin/docker kill heapster
ExecStartPre=-/usr/bin/docker rm -f heapster
ExecStart=/bin/bash -c "source /etc/environment && /usr/bin/docker run --name heapster -p 8082:8082 -e SINK=influxdb -e INFLUXDB_HOST=http://10.21.12.35:8086 -e FLAGS=\"--source=cadvisor:coreos?fleetEndpoint=http://$COREOS_PUBLIC_IPV4:4001\" kubernetes/heapster:v0.11.0"
ExecStop=/usr/bin/docker stop -t 2 heapster
```
