### ISSUE TITLE
Broken link in heapster/blob/master/docs/influxdb.md

### ISSUE THREAD

**Issue by swordphilic** [GoogleCloudPlatform/heapster#306]
Link embedded in "Controller Spec" at the end of the document is broken and returning 404.
The link redirects to <https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/deploy/kube-config/influxdb/influxdb-grafana-controller.yaml> which return 404. The correct link should be
<https://github.com/GoogleCloudPlatform/heapster/blob/master/deploy/kube-config/influxdb/influxdb-grafana-controller.json>.

**Comment by vishh** [comment]
Thanks for reporting the issue @swordphilic!
