### ISSUE TITLE
Namespaced containers stats aren't reported

### ISSUE THREAD

**Issue by josselin-c** [GoogleCloudPlatform/heapster#31]
Not sure if it's a problem with cAdvisor, Heapster or Kubernetes but using [kubernetes setup for monitoring](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/monitoring) I don't see in grafana pods started in namespaces other than the default one.

**Comment by vishh** [comment]
Keeping this open until a new heapster release is completed.

**Comment by vishh** [comment]
This required a change to kubelet. Waiting for a kubernetes release with that change to rollout.
