### ISSUE TITLE
Using remote etcd not currently possible

### ISSUE THREAD

**Issue by krancour** [GoogleCloudPlatform/heapster#318]
Various CoreOS cluster architectures are documented here:

https://coreos.com/docs/cluster-management/setup/cluster-architectures/

But this one in particular is most applicable to large and/or production clusters:

https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services

The hallmark of that architecture is that common services like etcd (for example) are isolated to a small, fixed number of nodes, while a larger number of less remarkable "worker nodes" is permitted to autoscale.  Such worker nodes do not run etcd.

Currently, it does not seem possible to run heapster on such "worker nodes" that are dependent on _remote_ etcd peers.

**Comment by vishh** [comment]
Heapster does not use etcd. To monitor a coreos cluster, heapster needs
access to fleet server(s), which can run locally or remotely.

**Comment by krancour** [comment]
> Heapster does not use etcd.

But Fleet _uses_ etcd.  From the Fleet documentation:

> fleetctl currently requires direct communication with the etcd cluster that your fleet machines are configured to use.

I see this repeatedly in my logs when I try to start heapster on a machine that isn't also running etcd:

```
Jun 08 19:28:28 ip-10-0-1-251 bash[1673]: INFO client.go:291: Failed getting response from http://:4001/: dial tcp :4001: connection refused
Jun 08 19:28:28 ip-10-0-1-251 bash[1673]: ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 1s
```

Port 4001 is an etcd port.

**Comment by vishh** [comment]
Heapster should be able to use a remote fleet server. Look [here](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/source-configuration.md#coreos).

**Comment by krancour** [comment]
Thanks.  That helped!
