### ISSUE TITLE
Heapster should use master proxy to nodes rather than going direct to kubelet

### ISSUE THREAD

**Issue by jimmidyson** [GoogleCloudPlatform/heapster#325]
In a secure environment all access to the kubelet will be locked down to only coming from the master, potentially with client cert authentication on the kubelet (as is the case of OpenShift by ootb).

As access to the API server is already secured & used to list nodes, etc the API server proxy can be used instead of going direct to the kubelet using the URL:

`https://MASTER/api/v1beta3/proxy/nodes/NODE/stats/POD`

**Comment by jimmidyson** [comment]
@vishh I think this should be the default once implemented. What do you think?

**Comment by vishh** [comment]
AFAIK the current api-server proxy isn't designed to handle metrics kind of
workloads. The plan was to expose a read-only 'http' endpoints on the
kubelet which exports metrics. Is this not an option for OpenShift?

**Comment by jimmidyson** [comment]
@vishh It might be :) Let me find out.

**Comment by jimmidyson** [comment]
Discussing in https://github.com/openshift/origin/issues/3020

**Comment by jimmidyson** [comment]
@vishh OK agree that this shouldn't go through the API server, will work on sorting out heapster & openshift separately.
