### ISSUE TITLE
host_id label only populated some of the time

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/heapster#348]
In the heapster 0.14.1 HTTP API, only some of the timeseries I'm receiving come with host_id populated, even though hostname is always populated.

In a default kubernetes cluster with no custom pods running, it looks like host_id is populated for the "/system", "/kubelet", "/kube-proxy", and "/docker-daemon", but not for anything else (i.e. "machine" or any actual pods).

**Comment by vishh** [comment]
:( Its a one line fix. I just sent out the PR. I can make a patch release quickly if that will help. I started working on better test coverage, which should have caught this issue.

**Comment by a-robinson** [comment]
I don't seem to have reopen privileges, but this appears to still not be working in 0.14.2. Only pods have host_id populated, not the non-pod containers (system, kubelet, etc.)
