### ISSUE TITLE
Heapster is not working with GCM

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/heapster#381]
When I start Heapster in version 0.15.0 (or from HEAD) and GCM sink enabled I get an error:
```
E0701 11:44:50.095197       1 heapster.go:59] Get https://www.googleapis.com/cloudmonitoring/v2beta2/projects/marine-bison-90112/metricDescriptors: x509: failed to load system roots and no roots provided
```
and Heapster is crashlooping.

There is a problem with SSL, probably after #376 is merged. There are few possible solutions:
* use other image as a base for Heapster one like [justicefries/busybox-ssl](https://registry.hub.docker.com/u/justicefries/busybox-ssl/dockerfile/)
* add the same commands to Heapster Dockerfile
* revert part of the mentioned PR which mount ssl certs

**Comment by vishh** [comment]
Reverting the config changes SGTM.
