### ISSUE TITLE
heapster looks for token despite attempting to disable authentication

### ISSUE THREAD

**Issue by DreadPirateShawn** [GoogleCloudPlatform/heapster#392]
I've got a kubernetes cluster working fine, and am trying to run heapster as a separate process with `--source` pointing to kubernetes master.

Currently authentication is disabled on our kubernetes cluster, so I'm trying to follow https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/source-configuration.md which says:

```
To run without auth file, use the following config:
--source=kubernetes:http://kubernetes-ro?auth=""
```

However, every permutation I've tried throws an error from attempting to load a token that doesn't exist:

```
$ heapster --v=5 --logtostderr=true --port=8082 --source=kubernetes:10.0.0.2:8080?auth=''
I0707 22:47:11.998806    3181 heapster.go:52] /my/bin/heapster --v=5 --logtostderr=true --port=8082 --source=kubernetes:10.0.0.2:8080?auth=
I0707 22:47:11.998935    3181 heapster.go:53] Heapster version 0.16.0
E0707 22:47:11.999030    3181 heapster.go:59] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

Attempts include the following, all with the same error:
```
--source=kubernetes:10.0.0.2:8080?auth=''
--source=kubernetes:http://10.0.0.2:8080?auth=''
--source=kubernetes:10.0.0.2?auth=''
--source=kubernetes:http://10.0.0.2?auth=''
--source=kubernetes:10.0.0.2:8080-ro?auth=''
--source=kubernetes:http://10.0.0.2:8080-ro?auth=''
--source=kubernetes:10.0.0.2-ro?auth=''
--source=kubernetes:http://10.0.0.2-ro?auth=''
--source=kubernetes:http://kubernetes-ro?auth=""
```

The `-ro` after the IP looks admittedly silly, granted, but I wanted to be thorough. :-)

I'm trying to determine how to combine the base `--source=kubernetes:<KUBERNETES_MASTER>[?<KUBERNETES_OPTIONS>]` flag with the `?auth=""` option. 

The doc does note:

> Note: Remove "monitoring-token" volume from heaspter controller config if you are running without auth.

However, I'm not running heapster via the controller config, so how would that translate to direct process flags?

**Comment by DreadPirateShawn** [comment]
I've also tried adding the `insecure=true` option found later in the same doc, with the same failure, eg:
```
$ /my/bin/heapster --v=5 --logtostderr=true --port=8082 --source=kubernetes:http://10.0.0.2:8080?insecure=true\&auth=''
I0708 15:55:16.246421    5602 heapster.go:52] /my/bin/heapster --v=5 --logtostderr=true --port=8082 --source=kubernetes:10.0.0.2:8080?insecure=true&auth=
I0708 15:55:16.246602    5602 heapster.go:53] Heapster version 0.16.0
E0708 15:55:16.246703    5602 heapster.go:59] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by DreadPirateShawn** [comment]
As I read through the source and issues, I'm starting to beg the question -- now that cadvisor has been integrated into kubernetes, is it even possible to run heapster as a separate process and still tie into the kubernetes cluster?

I've got some dev work in progress which implements a new sink for heapster, so it seems like running heapster directly during dev / fix cycles would allow for more speed / flexibility, but is that even an option anymore?

**Comment by jimmidyson** [comment]
@DreadPirateShawn As heapster needs to query the API server to retrieve the list of hosts, some kind of authorization has to take place, be it cert/token via service account/basic auth. There's no reason not to be able to use heapster externally from the cluster, but currently you would need to provide the same config as if it was inside a cluster. Looking at the code, it might be a good idea to add more options for auth to facilitate what you're doing.

**Comment by DreadPirateShawn** [comment]
Hmm. In the kubernetes cluster, authentication is currently disabled -- using neither cert nor token -- so it is using the same config... does that mean that even if I switch to loading heapster inside the cluster, it'll still fail in the same manner? That is, does heapster (currently) require that some authentication is in place?

**Comment by jimmidyson** [comment]
Are you using master? If so can you try with inClusterConfig=false as an extra option to the kube source?

**Comment by DreadPirateShawn** [comment]
Fantastic -- this gets me further:
```
/my/bin/heapster --v=5 --logtostderr=true --port=8082 --source="kubernes:http://10.0.0.2:8080?insecure=true&inClusterConfig=false"

I0708 18:45:58.212246    7140 heapster.go:53] Heapster version 0.16.0
I0708 18:45:58.213190    7140 kube_factory.go:169] Using Kubernetes client with master "http://10.0.0.2:8080" and version "v1"
I0708 18:45:58.213234    7140 kube_factory.go:170] Using kubelet port 10255
I0708 18:45:58.213314    7140 kube_events.go:153] Starting "kube-events" source
I0708 18:45:58.213338    7140 kube_events.go:155] Finished starting "kube-events" source
I0708 18:45:58.215322    7140 heapster.go:64] Starting heapster on port 8082
I0708 18:45:58.215526    7140 manager.go:84] starting to scrape data from sources
I0708 18:45:58.223577    7140 manager.go:66] attempting to get data from source "Kube Pods Source"
```

Granted, I'm seeing other errors now:
```
E0708 18:45:58.225355    7140 reflector.go:136] Failed to list *api.Pod: field label not supported: spec.nodeName
```
... but now I can dig into the code and get more info, and file separate tickets if needed. Closing this ticket.

Many thanks!

**Comment by jimmidyson** [comment]
@DreadPirateShawn Glad it's working-ish for you now.
