### ISSUE TITLE
Tag v0.16.0 missing from repository

### ISSUE THREAD

**Issue by echu** [GoogleCloudPlatform/heapster#393]
I have a kubernetes cluster running on GCE and followed the steps outlined in the [tutorial](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/google.md). However, I'm seeing the following message in my logs.

```
Failed to pull image "kubernetes/heapster:v0.16.0" from pod "monitoring-heapster-controller-jskpj_default" and container "heapster": Tag v0.16.0 not found in repository kubernetes/heapster
```

I'm not sure if this is supposed to be pulling from Dockerhub, but a cursory glance at the [tags](https://registry.hub.docker.com/u/kubernetes/heapster/tags/manage/) there seems to confirm that the v0.16.0 tag was not pushed to Dockerhub.

**edit**: forgot to mention that this was with the latest commit, fc13ee3bd0a3bc0f2c9bfd245c032286b5d82c74.

**Comment by DreadPirateShawn** [comment]
I'm seeing the same thing, attempting to run `kubectl.sh create -f deploy/kube-config/influxdb` out-of-the-box.

Spot-checked via docker directly:
```
$ docker run kubernetes/heapster:v0.16.0
Unable to find image 'kubernetes/heapster:v0.16.0' locally
Pulling repository kubernetes/heapster
FATA[0005] Tag v0.16.0 not found in repository kubernetes/heapster
```

**Comment by vmarmol** [comment]
Apologies, we uploaded to gcr.io, but not Docker Hub. Should be up now!
