### ISSUE TITLE
Export the machine container with the proper CPU limit

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/heapster#399]
Today we convert shares to CPU limit, but this doesn't work for the root container since it always has 1024 shares even though it corresponds to all cores on the machine. We should take the NumCores from the machine and export that instead.

**Comment by piosz** [comment]
I can take a look on Monday

**Comment by dchen1107** [comment]
cc/ @dchen1107

**Comment by dchen1107** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10760
