### ISSUE TITLE
Incorrect data type NodeList vs MinionList

### ISSUE THREAD

**Issue by mindscratch** [GoogleCloudPlatform/heapster#41]
I'm running Kubernetes 0.7.0 and Heapster 0.4.0 and I noticed the Heapster container exits after ~10 seconds. I see in its logs:

```
heapster.go:22] data of kind 'NodeList', obj of type 'MinionList'
```

**Comment by vishh** [comment]
Kubernetes v0.7.0 has an API issue. Kindly upgrade to the latest release
v0.7.2.
