### ISSUE TITLE
heapster  crashloop!

### ISSUE THREAD

**Issue by y00181991** [GoogleCloudPlatform/heapster#432]
I still got this error when heapster starts:

I0723 09:19:23.571136       1 heapster.go:52] /heapster --source=kubernetes:'' --sink=gcl --sink=influxdb:http://monitoring-influxdb:8086 --poll_duration=2m --stats_resolution=1m
I0723 09:19:23.571242       1 heapster.go:53] Heapster version 0.16.0
E0723 09:19:23.571299       1 heapster.go:59] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

and I use the default heapster-controller.yaml

kubernetes  version:
Client Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-127-gc6161824db3784-dirty", GitCommit:"c6161824db3784e6156131307a5e94647e5557fd", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-127-gc6161824db3784-dirty", GitCommit:"c6161824db3784e6156131307a5e94647e5557fd", GitTreeState:"dirty"}

**Comment by mikedanese** [comment]
can you post a link to the heapster-controller.yaml

**Comment by y00181991** [comment]
/kubernetes/cluster/addons/cluster-monitoring/standalone$ kubectl create -f heapster-controller.yaml

heapster-controller.yaml 

  1 apiVersion: v1                                                                                                                                                                     
  2 kind: ReplicationController
  3 metadata:
  4   name: monitoring-heapster-v5
  5   namespace: kube-system
  6   labels:
  7     k8s-app: heapster
  8     version: v5
  9     kubernetes.io/cluster-service: "true"
 10 spec:
 11   replicas: 1
 12   selector:
 13     k8s-app: heapster
 14     version: v5
 15   template:
 16     metadata:
 17       labels:
 18         k8s-app: heapster
 19         version: v5
 20         kubernetes.io/cluster-service: "true"
 21     spec:
 22       containers:
 23         - image: gcr.io/google_containers/heapster:v0.16.0
 24           name: heapster
 25           resources:
 26             limits:
 27               cpu: 100m
 28               memory: 200Mi
 29           command:
 30             - /heapster
 31             - --source=kubernetes:''

**Comment by y00181991** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.16.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes:''

**Comment by y00181991** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.16.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes:''

**Comment by y00181991** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.16.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes:''
