### ISSUE TITLE
Pods that no longer exist not being garbage collected from v1 HTTP API

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/heapster#446]
I'll look into the root cause, but I'm seeing this behavior on 0.15.0. Any idea of whether it's been fixed since would be helpful.

@vishh @vmarmol

**Comment by vishh** [comment]
This is likely an issue. I don't think heapster purges pods whenever it
notices a delete event from Kube API server currently.

**Comment by vishh** [comment]
This can cause memory leaks since the internal metrics store does not garbage collect once we stop writing metrics. I am working on fixing this now.
