### ISSUE TITLE
Not getting graphs on heapster UI. 

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/heapster#76]
Below are the pods running on my system -

NAME        |   IMAGE(S)     |                   HOST              |            LABELS                  |        STATUS
f95a0a29-a78e-11e4-b11e-984be16ce9ba | kubernetes/heapster_influxdb:v0.2 |       10.227.125.10/10.227.125.10 |  name=influxGrafana   |                    Running
                                       kubernetes/heapster_grafana:v0.2

773cf11c-a78f-11e4-b11e-984be16ce9ba |  kubernetes/heapster:v0.5 |                 10.227.125.10/10.227.125.10 |  name=heapster,uses=monitoring-influxdb |  Running
cf7bfe93-a78e-11e4-b11e-984be16ce9ba  | google/cadvisor:0.8.0 |                   10.227.125.10/10.227.125.10 |  name=cadvisor  |                          Running
cf7bb0a1-a78e-11e4-b11e-984be16ce9ba |  google/cadvisor:0.8.0      |              10.227.125.3/10.227.125.3  |   name=cadvisor     |                       Running

Have two minions -

NAME                LABELS
10.227.125.10       <none>
10.227.125.3        <none>

When I query curl -v http://10.227.125.10:10250/stats/, I get below errors -

* Hostname was NOT found in DNS cache
*   Trying 10.227.125.10...
* Connected to 10.227.125.10 (10.227.125.10) port 10250 (#0)
> GET /stats/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.227.125.10:10250
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 29 Jan 2015 09:07:15 GMT
< Content-Length: 39
<
Internal Error: no cadvisor connection
* Connection #0 to host 10.227.125.10 left intact

While trying with curl -v http://10.227.125.3:10250/stats/heapster/heapster/, getting below errors -

* Hostname was NOT found in DNS cache
*   Trying 10.227.125.3...
* Connected to 10.227.125.3 (10.227.125.3) port 10250 (#0)
> GET /stats/heapster/heapster/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.227.125.3:10250
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 29 Jan 2015 09:19:06 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.227.125.3 left intact
{}

No graph displayed at heapster UI. Please suggest where it is going wrong?

**Comment by sourav82** [comment]
These minions are on local intranet (running ubuntu). Not using any cloud infrastructure. It is local Kubernetes cluster having two minions.

**Comment by vishh** [comment]
Can you check if `cadvisor` is running on all your nodes?

**Comment by sourav82** [comment]
@vishh, Yes, cadvisor is reachable using http://<minion_ip>:4194/.

**Comment by sourav82** [comment]
@vishh, I was using kubernetes-mesos framework with mesos and came to know that cadvisor is not yet integrated with kubernetes-mesos. https://github.com/mesosphere/kubernetes-mesos/issues/137#issuecomment-72027269
