### ISSUE TITLE
Parallelize Heapster Core

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/heapster#91]
Allow the Heapster core to fetch and export multiple streams simultaneously. This should also entail work to allow a single stream to fall behind and be robust to node failures.

**Comment by arkadijs** [comment]
For InfluxDB sink I suggest to use Go channels and a separate flusher goroutine together with GOMAXPROCS.
https://github.com/arkadijs/heapster/blob/master/sinks/influxdb.go#L209

**Comment by vishh** [comment]
This has been fixed on head. The sinks themselves do not run in parallel yet.
