### ISSUE TITLE
lastQuery handling in cAdvisor source is wrong

### ISSUE THREAD

**Issue by arkadijs** [GoogleCloudPlatform/heapster#97]
There are two issues:

1. `lastQuery` is not set in the loop, resulting in data duplication, because cAdvisor returns last 64 stats instead. Example fix:
https://github.com/arkadijs/heapster/commit/2fc23c2a890e6c77c56ee0640e5601178f461df6#diff-3917589e63e61c59289ec2acb14ebcc8R66

2. On a medium to large cluster with medium to large number of containers the logic of one lastQuery per all peers would be flawed anyway. It leads to missing data points because Heapster+cAdvisor are not fast enough and Heapster queries all cAdvisor instances serially. A crappy fix that works in practice:
https://github.com/arkadijs/heapster/commit/2fc23c2a890e6c77c56ee0640e5601178f461df6#diff-3917589e63e61c59289ec2acb14ebcc8R37

**Comment by vishh** [comment]
Thanks for reporting the issue. 
I wonder if we can eliminate `lastQuery` completely and instead just use `poll_duration`?
We have just started working towards improving the core, and eventually scalability as well. I can imagine polling all cadvisor's in parallel at the least, in the short term. We are aiming for sharding heapster itself from ground up, but that might not happen soon.

**Comment by arkadijs** [comment]
Also, adding to (1), numStats is not a cAdvisor HTTP query parameter, but must be supplied via POST JSON: https://github.com/arkadijs/heapster/commit/2fc23c2a890e6c77c56ee0640e5601178f461df6#diff-d506dd5ceb65926ead27b28cd6c5eca3L95

**Comment by vishh** [comment]
This has been fixed.
